//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeliosPlus.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HeliosPlus.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Active].
        /// </summary>
        internal static string _Active_ {
            get {
                return ResourceManager.GetString("_Active_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CLONE].
        /// </summary>
        internal static string _CLONE_ {
            get {
                return ResourceManager.GetString("_CLONE_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Profiles.
        /// </summary>
        internal static string Active_Profiles {
            get {
                return ResourceManager.GetString("Active_Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another instance of this program is in working state. Please close other instances before trying to switch profile..
        /// </summary>
        internal static string Another_instance_of_this_program_is_in_working_state_Please_close_other_instances_before_trying_to_switch_profile {
            get {
                return ResourceManager.GetString("Another_instance_of_this_program_is_in_working_state_Please_close_other_instances" +
                        "_before_trying_to_switch_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Apply.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply_Profile.
        /// </summary>
        internal static string Apply_Profile {
            get {
                return ResourceManager.GetString("Apply_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string Are_you_sure {
            get {
                return ResourceManager.GetString("Are_you_sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments.
        /// </summary>
        internal static string Arguments {
            get {
                return ResourceManager.GetString("Arguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not change active profile..
        /// </summary>
        internal static string Can_not_change_active_profile {
            get {
                return ResourceManager.GetString("Can_not_change_active_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not open a named pipe for Inter-process communication..
        /// </summary>
        internal static string Can_not_open_a_named_pipe_for_Inter_process_communication {
            get {
                return ResourceManager.GetString("Can_not_open_a_named_pipe_for_Inter_process_communication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C&amp;lone.
        /// </summary>
        internal static string Clone {
            get {
                return ResourceManager.GetString("Clone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Helios Shortcut.
        /// </summary>
        internal static string Create_Helios_Shortcut {
            get {
                return ResourceManager.GetString("Create_Helios_Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C&amp;reate Shortcut.
        /// </summary>
        internal static string Create_Shortcut {
            get {
                return ResourceManager.GetString("Create_Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Current].
        /// </summary>
        internal static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 180°.
        /// </summary>
        internal static string Degree180 {
            get {
                return ResourceManager.GetString("Degree180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 270°.
        /// </summary>
        internal static string Degree270 {
            get {
                return ResourceManager.GetString("Degree270", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 90°.
        /// </summary>
        internal static string Degree90 {
            get {
                return ResourceManager.GetString("Degree90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion.
        /// </summary>
        internal static string Deletion {
            get {
                return ResourceManager.GetString("Deletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile &apos;{0}&apos;.
        /// </summary>
        internal static string Edit_Profile {
            get {
                return ResourceManager.GetString("Edit_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable.
        /// </summary>
        internal static string Executable {
            get {
                return ResourceManager.GetString("Executable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable Address.
        /// </summary>
        internal static string Executable_Address {
            get {
                return ResourceManager.GetString("Executable_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable address can not be empty..
        /// </summary>
        internal static string Executable_address_can_not_be_empty {
            get {
                return ResourceManager.GetString("Executable_address_can_not_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable file not found..
        /// </summary>
        internal static string Executable_file_not_found {
            get {
                return ResourceManager.GetString("Executable_file_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable Files|*.exe.
        /// </summary>
        internal static string Executable_Files_Filter {
            get {
                return ResourceManager.GetString("Executable_Files_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing &apos;{0}&apos; with &apos;{1}&apos; profile..
        /// </summary>
        internal static string Executing_application_with_profile {
            get {
                return ResourceManager.GetString("Executing_application_with_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create the shortcut. Unexpected exception occurred..
        /// </summary>
        internal static string Failed_to_create_the_shortcut_Unexpected_exception_occurred {
            get {
                return ResourceManager.GetString("Failed_to_create_the_shortcut_Unexpected_exception_occurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save profile..
        /// </summary>
        internal static string Failed_to_save_profile {
            get {
                return ResourceManager.GetString("Failed_to_save_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Error.
        /// </summary>
        internal static string Fatal_Error {
            get {
                return ResourceManager.GetString("Fatal_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game&apos;s AppId.
        /// </summary>
        internal static string Games_AppId {
            get {
                return ResourceManager.GetString("Games_AppId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helios Display Management.
        /// </summary>
        internal static string Helios_Display_Management {
            get {
                return ResourceManager.GetString("Helios_Display_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helios Display Management - Please Wait.
        /// </summary>
        internal static string Helios_Display_Management_Please_Wait {
            get {
                return ResourceManager.GetString("Helios_Display_Management_Please_Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Installed].
        /// </summary>
        internal static string Installed {
            get {
                return ResourceManager.GetString("Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or duplicate profile name..
        /// </summary>
        internal static string Invalid_or_duplicate_profile_name {
            get {
                return ResourceManager.GetString("Invalid_or_duplicate_profile_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It won&apos;t be long now.
        /// </summary>
        internal static string It_wont_be_long_now {
            get {
                return ResourceManager.GetString("It_wont_be_long_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [None].
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Available.
        /// </summary>
        internal static string Not_Available {
            get {
                return ResourceManager.GetString("Not_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Not Installed].
        /// </summary>
        internal static string Not_Installed {
            get {
                return ResourceManager.GetString("Not_Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Not Owned].
        /// </summary>
        internal static string Not_Owned {
            get {
                return ResourceManager.GetString("Not_Owned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Failed: {0}.
        /// </summary>
        internal static string Operation_Failed {
            get {
                return ResourceManager.GetString("Operation_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Place Shortcut.
        /// </summary>
        internal static string Place_Shortcut {
            get {
                return ResourceManager.GetString("Place_Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait ....
        /// </summary>
        internal static string Please_wait {
            get {
                return ResourceManager.GetString("Please_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press ESC to cancel.
        /// </summary>
        internal static string Press_ESC_to_cancel {
            get {
                return ResourceManager.GetString("Press_ESC_to_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Information.
        /// </summary>
        internal static string Process_Information {
            get {
                return ResourceManager.GetString("Process_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile is invalid or not possible to apply..
        /// </summary>
        internal static string Profile_is_invalid_or_not_possible_to_apply {
            get {
                return ResourceManager.GetString("Profile_is_invalid_or_not_possible_to_apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Name:.
        /// </summary>
        internal static string Profile_Name {
            get {
                return ResourceManager.GetString("Profile_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles:.
        /// </summary>
        internal static string Profiles {
            get {
                return ResourceManager.GetString("Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverting in ....
        /// </summary>
        internal static string Reverting_in {
            get {
                return ResourceManager.GetString("Reverting_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Running].
        /// </summary>
        internal static string Running {
            get {
                return ResourceManager.GetString("Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and &amp;Apply.
        /// </summary>
        internal static string Save_and_Apply {
            get {
                return ResourceManager.GetString("Save_and_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Profiles.
        /// </summary>
        internal static string Saved_Profiles {
            get {
                return ResourceManager.GetString("Saved_Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected file is not a valid executable file..
        /// </summary>
        internal static string Selected_file_is_not_a_valid_executable_file {
            get {
                return ResourceManager.GetString("Selected_file_is_not_a_valid_executable_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Profile:.
        /// </summary>
        internal static string Selected_Profile {
            get {
                return ResourceManager.GetString("Selected_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected profile is invalid or not found..
        /// </summary>
        internal static string Selected_profile_is_invalid_or_not_found {
            get {
                return ResourceManager.GetString("Selected_profile_is_invalid_or_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected profile is not possible..
        /// </summary>
        internal static string Selected_profile_is_not_possible {
            get {
                return ResourceManager.GetString("Selected_profile_is_not_possible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut.
        /// </summary>
        internal static string Shortcut {
            get {
                return ResourceManager.GetString("Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut placed successfully..
        /// </summary>
        internal static string Shortcut_placed_successfully {
            get {
                return ResourceManager.GetString("Shortcut_placed_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcuts|*.lnk.
        /// </summary>
        internal static string Shortcuts_Filter {
            get {
                return ResourceManager.GetString("Shortcuts_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standalone Process.
        /// </summary>
        internal static string Standalone_Process {
            get {
                return ResourceManager.GetString("Standalone_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting in ....
        /// </summary>
        internal static string Starting_in {
            get {
                return ResourceManager.GetString("Starting_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam executable file not found..
        /// </summary>
        internal static string Steam_executable_file_not_found {
            get {
                return ResourceManager.GetString("Steam_executable_file_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam Game.
        /// </summary>
        internal static string Steam_Game {
            get {
                return ResourceManager.GetString("Steam_Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam game is not installed..
        /// </summary>
        internal static string Steam_game_is_not_installed {
            get {
                return ResourceManager.GetString("Steam_game_is_not_installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam game is not owned..
        /// </summary>
        internal static string Steam_game_is_not_owned {
            get {
                return ResourceManager.GetString("Steam_game_is_not_owned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam Games.
        /// </summary>
        internal static string Steam_Games {
            get {
                return ResourceManager.GetString("Steam_Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam is not installed..
        /// </summary>
        internal static string Steam_is_not_installed {
            get {
                return ResourceManager.GetString("Steam_is_not_installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switching display profile to &apos;{0}&apos;..
        /// </summary>
        internal static string Switching_display_profile_to_profile {
            get {
                return ResourceManager.GetString("Switching_display_profile_to_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporarily switch with process monitoring.
        /// </summary>
        internal static string Temporarily_switch_with_process_monitoring {
            get {
                return ResourceManager.GetString("Temporarily_switch_with_process_monitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This profile is currently impossible to apply..
        /// </summary>
        internal static string This_profile_is_currently_impossible_to_apply {
            get {
                return ResourceManager.GetString("This_profile_is_currently_impossible_to_apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        internal static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topologies.
        /// </summary>
        internal static string Topologies {
            get {
                return ResourceManager.GetString("Topologies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Updating].
        /// </summary>
        internal static string Updating {
            get {
                return ResourceManager.GetString("Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        internal static string Validation {
            get {
                return ResourceManager.GetString("Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for the &apos;{0}&apos; to terminate.
        /// </summary>
        internal static string Waiting_for_the_0_to_terminate {
            get {
                return ResourceManager.GetString("Waiting_for_the_0_to_terminate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting Process.
        /// </summary>
        internal static string Waiting_Process {
            get {
                return ResourceManager.GetString("Waiting_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} x {1}.
        /// </summary>
        internal static string X_x_Y {
            get {
                return ResourceManager.GetString("X_x_Y", resourceCulture);
            }
        }
    }
}
